const $=(s,r=document)=>r.querySelector(s),esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const base=document.body.dataset.base||'',page=document.body.dataset.page;
document.documentElement.dataset.theme=S.get('theme','light');
function toast(m){const t=document.createElement('div');t.className='toast';t.setAttribute('role','status');t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),2500)}
const NAV={STUDENT:[['dashboard','Dashboard'],['diagnostic','Diagnostic'],['practice','Practice'],['mock-tests','Mock Tests'],['coding','Coding'],['interview','AI Interview'],['chat','AI Assistant'],['analytics','Analytics'],['recommendations','Recommendations'],['achievements','Achievements'],['reports','Reports'],['profile','Profile'],['settings','Settings']],
FACULTY:[['faculty/dashboard','Dashboard'],['faculty/students','Students'],['faculty/questions','Question Bank'],['settings','Settings']],
ADMIN:[['admin/dashboard','Dashboard'],['admin/users','Users'],['admin/questions','Questions'],['settings','Settings']]};
const attempts=()=>S.get('attempts',[]);
function stats(){const a=attempts(),t={};let c=0,n=0,perfect=false;a.forEach(x=>{c+=x.score;n+=x.total;if(x.score===x.total&&x.total)perfect=true;Object.entries(x.topics||{}).forEach(([k,v])=>{t[k]=t[k]||[0,0];t[k][0]+=v[0];t[k][1]+=v[1]})});
 const tp=Object.entries(t).map(([k,v])=>[k,Math.round(v[0]/v[1]*100)]);return{n:a.length,solved:n,acc:n?Math.round(c/n*100):0,tp,weak:tp.filter(x=>x[1]<70).map(x=>x[0]),strong:tp.filter(x=>x[1]>=80).map(x=>x[0]),perfect,iv:S.get('interviews',0),code:S.get('codeSolved',0)}}
function shuffle(a){return[...a].sort(()=>Math.random()-.5)}
function bar(p){return`<div class=bar role=progressbar aria-valuenow=${p}><i style="width:${p}%"></i></div>`}
function stat(l,v){return`<div class="card stat"><span>${l}</span><b>${v}</b></div>`}
function addXP(x){const us=S.get('users'),u=us.find(z=>z.id===S.get('me'));if(u&&u.role==='STUDENT'){u.xp+=x;u.level=Math.max(u.level,Math.floor(u.xp/200)+1);S.set('users',us)}}

function quiz(el,qs,secs,title,kind){qs=qs.map(q=>{const c=q.o[0];return{...q,o:shuffle(q.o),c}});let i=0,a={},m={},left=secs,tm;
 const done=()=>{clearInterval(tm);let sc=0,tp={};qs.forEach((q,k)=>{const ok=q.o[a[k]]===q.c;sc+=ok;tp[q.topic]=tp[q.topic]||[0,0];tp[q.topic][0]+=ok;tp[q.topic][1]++});
  const at=attempts();at.push({title,kind,score:sc,total:qs.length,ts:Date.now(),topics:tp});S.set('attempts',at);addXP(sc*10);const weak=Object.entries(tp).filter(([k,v])=>v[0]/v[1]<.7).map(x=>x[0]);
  el.innerHTML=`<div class=card><h2>Result: ${sc}/${qs.length} (${Math.round(sc/qs.length*100)}%)</h2><p>+${sc*10} XP. Weak topics: ${weak.join(', ')||'none'}</p><p><b>Recommended:</b> ${AI.generateRecommendation(weak).join(' · ')}</p>`+qs.map((q,k)=>`<div class=card><b>${k+1}. ${esc(q.q)}</b>${q.o.map((o,j)=>`<div class="opt ${o===q.c?'ok':j===a[k]?'no':''}">${esc(o)}</div>`).join('')}<p class=mu>${esc(q.e)}</p></div>`).join('')+`</div>`;toast('Test submitted')};
 const draw=()=>{const q=qs[i];el.innerHTML=`<div class=card><div class=row><b>${esc(title)}</b><span class=pill id=tm></span></div>${bar((i+1)/qs.length*100)}<h3>Q${i+1}/${qs.length}. ${esc(q.q)}</h3>${q.o.map((o,k)=>`<button class="opt${a[i]===k?' sel':''}" data-k=${k}>${esc(o)}</button>`).join('')}<div class=row><button data-a=prev>Previous</button><button data-a=mark>${m[i]?'Unmark':'Mark'} for review</button><button data-a=next>Next</button><button class=pri data-a=submit>Submit</button></div><div class=nav>${qs.map((_,k)=>`<button data-g=${k} class="${a[k]!=null?'done':''} ${m[k]?'mk':''}" aria-label="Question ${k+1}">${k+1}</button>`).join('')}</div></div>`;tick()};
 const tick=()=>{const t=$('#tm',el);if(t){t.textContent=Math.floor(left/60)+':'+String(left%60).padStart(2,'0');t.className='pill'+(left<30?' warn':'')}};
 el.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.k!=null)a[i]=+b.dataset.k;if(b.dataset.g!=null)i=+b.dataset.g;const x=b.dataset.a;if(x==='next')i=Math.min(qs.length-1,i+1);if(x==='prev')i=Math.max(0,i-1);if(x==='mark')m[i]=!m[i];if(x==='submit'){if(confirm('Submit test?'))return done();return}draw()};
 tm=setInterval(()=>{left--;tick();if(left<=0)done()},1000);draw()}

function table(rows,cols,actions){return rows.length?`<div style="overflow-x:auto"><table><tr>${cols.map(c=>`<th>${c[0]}</th>`).join('')}${actions?'<th></th>':''}</tr>${rows.map((r,i)=>`<tr>${cols.map(c=>`<td>${esc(r[c[1]])}</td>`).join('')}${actions?`<td><button data-del=${i}>Delete</button></td>`:''}</tr>`).join('')}</table></div>`:'<p class=mu>Nothing here yet.</p>'}
function makeChart(id,type,labels,data,label){if(window.Chart&&$('#'+id))new Chart($('#'+id),{type,data:{labels,datasets:[{label,data,backgroundColor:['#4f7bff','#8b5cf6','#22d3ee','#22c55e','#f59e0b','#ef4444'],borderColor:'#4f7bff',tension:.3}]}})}

const P={
dashboard(el,u){const s=stats(),at=attempts().slice(-3).reverse();el.innerHTML=`<h1>Welcome back, ${esc(u.name.split(' ')[0])}</h1><div class=grid>${stat('Streak',(u.streak||0)+' days')}${stat('XP',u.xp||0)}${stat('Level',u.level||1)}${stat('Accuracy',s.acc+'%')}${stat('Questions solved',s.solved)}</div>
 <div class=grid><div class=card><h3>Weak topics</h3>${s.weak.length?s.weak.map(esc).join(', '):'None. Great!'}</div><div class=card><h3>Recommended for you</h3>${AI.generateRecommendation(s.weak,u.goal).map(esc).join('<br>')}</div></div>
 <div class=card><h3>Recent tests</h3>${at.length?at.map(x=>`<p>${esc(x.title)}: ${x.score}/${x.total}${bar(x.score/x.total*100)}</p>`).join(''):'<p class=mu>No attempts yet. <a href="practice.html">Start practicing</a></p>'}</div>
 <div class=card><h3>Performance</h3><canvas id=c1 height=90></canvas></div>`;const a=attempts();makeChart('c1','line',a.map((x,i)=>'#'+(i+1)),a.map(x=>Math.round(x.score/x.total*100)),'Score %')},
practice(el){const qs=S.get('questions',Q0),subs=[...new Set(qs.map(q=>q.subject))];el.innerHTML=`<h1>Practice</h1><div class=card><label>Subject</label><select id=su><option>All</option>${subs.map(s=>`<option>${s}</option>`).join('')}</select><label>Difficulty</label><select id=df><option>All</option><option>Easy</option><option>Medium</option><option>Hard</option></select><label>Question count</label><input id=nq type=number value=5 min=1 max=20><button class=pri id=go>Start practice</button></div><div id=q></div>`;
 $('#go').onclick=()=>{let p=qs.filter(q=>($('#su').value==='All'||q.subject===$('#su').value)&&($('#df').value==='All'||q.diff===$('#df').value));if(!p.length)return $('#q').innerHTML='<div class=card>No questions match. Try other filters.</div>';p=shuffle(p).slice(0,+$('#nq').value||5);$('.card').style.display='none';quiz($('#q'),p,p.length*60,'Practice','practice')}},
'mock-tests'(el){const T=[['Aptitude Mock Test','Aptitude',6,300],['JavaScript Assessment','JavaScript',5,300],['Technical Mock Test','',10,600],['Core CS Test','DBMS',6,360]];el.innerHTML=`<h1>Mock Tests</h1><div class=grid id=tl>${T.map((t,i)=>`<div class=card><h3>${t[0]}</h3><p class=mu>${t[2]} questions · ${t[3]/60} min</p><button class=pri data-t=${i}>Start</button></div>`).join('')}</div><div id=q></div>`;
 $('#tl').onclick=e=>{const b=e.target.closest('[data-t]');if(!b)return;const t=T[b.dataset.t];let p=S.get('questions',Q0).filter(q=>!t[1]||q.subject===t[1]||(t[1]==='DBMS'&&['SQL','DBMS'].includes(q.subject)));p=shuffle(p).slice(0,t[2]);$('#tl').style.display='none';quiz($('#q'),p,t[3],t[0],'mock')}},
diagnostic(el){const p=shuffle(S.get('questions',Q0)).slice(0,8);el.innerHTML=`<h1>Diagnostic Assessment</h1><p class=mu>8 mixed questions to find your strengths and weak areas.</p><div id=q></div>`;quiz($('#q'),p,480,'Diagnostic','diagnostic')},
coding(el){const cur=CODING;let sel=cur[0];el.innerHTML=`<h1>Coding Practice</h1><div class=card><label>Problem</label><select id=pb>${cur.map(p=>`<option value=${p.id}>${p.t} (${p.d})</option>`).join('')}</select><p id=st></p><label>Language</label><select id=lg><option>JavaScript</option><option>Python</option><option>Java</option><option>C++</option></select><textarea id=cd rows=8 spellcheck=false></textarea><button class=pri id=rn>Run tests</button><p class=mu>Demo Code Execution: JavaScript runs in your browser; other languages are simulated.</p><div id=out></div></div>`;
 const load=()=>{sel=cur.find(p=>p.id==$('#pb').value);$('#st').textContent=sel.s;$('#cd').value=sel.fn};load();$('#pb').onchange=load;
 $('#rn').onclick=()=>{let res=[];if($('#lg').value==='JavaScript'){try{const f=new Function($('#cd').value+';return solve')();res=sel.tests.map(t=>{const r=f(...t[0]);return[JSON.stringify(t[0]),JSON.stringify(t[1]),JSON.stringify(r),JSON.stringify(r)===JSON.stringify(t[1])]})}catch(e){return $('#out').innerHTML='<p class=warn>Error: '+esc(e.message)+'</p>'}}else res=sel.tests.map(t=>[JSON.stringify(t[0]),JSON.stringify(t[1]),'(simulated)',$('#cd').value.length>40]);
  const ok=res.every(r=>r[3]);$('#out').innerHTML=res.map(r=>`<p>${r[3]?'✅':'❌'} input ${esc(r[0])} → expected ${esc(r[1])}, got ${esc(r[2])}</p>`).join('');if(ok){S.set('codeSolved',S.get('codeSolved',0)+1);addXP(30);toast('All tests passed')}}},
interview(el){el.innerHTML=`<h1>AI Mock Interview</h1><div class=card id=cfg><label>Job role</label><select id=rl>${['Frontend Developer','Backend Developer','Full Stack Developer','Java Developer','Python Developer','Data Analyst','AI/ML Engineer'].map(r=>`<option>${r}</option>`).join('')}</select><label>Interview type</label><select id=ty>${Object.keys(IQ).map(r=>`<option>${r}</option>`).join('')}</select><button class=pri id=go>Start interview</button></div><div id=iv></div>`;
 $('#go').onclick=()=>{const ty=$('#ty').value,used=[],rep=[];let n=0,cur;$('#cfg').style.display='none';const ask=q=>{cur=q||AI.generateQuestion(ty,used);used.push(cur[0]);$('#iv').innerHTML=`<div class=card><span class=pill>Question ${n+1}/3</span><h3>${esc(cur[0])}</h3><textarea id=an rows=5 placeholder="Type your answer"></textarea><button class=pri id=sb>Submit answer</button></div>`;$('#sb').onclick=()=>{const ans=$('#an').value;if(!ans.trim())return toast('Please type an answer');const ev=AI.evaluateAnswer(ans,cur[1]);rep.push(ev.score);n++;
  $('#iv').innerHTML=`<div class=card><h3>Evaluation: ${ev.score}/100</h3><p>Relevance ${ev.rel} · Correctness ${ev.cor} · Completeness ${ev.comp}</p><p>✅ ${esc(ev.strengths)}</p><p>Missing concepts: ${esc(ev.missing)}</p><p>Tip: ${esc(ev.tip)}</p><button class=pri id=nx>${n<3?'Next question':'Finish interview'}</button></div>`;
  $('#nx').onclick=()=>{if(n<3)return ask(n===1?[AI.generateFollowUp(ev),cur[1]]:null);S.set('interviews',S.get('interviews',0)+1);addXP(50);const h=S.get('ivh',[]);h.push({role:$('#rl').value,ty,avg:Math.round(rep.reduce((a,b)=>a+b)/rep.length)});S.set('ivh',h);$('#iv').innerHTML=`<div class=card><h2>Interview report</h2><p>${$('#rl').value} · ${ty}</p><p>Scores: ${rep.join(', ')}</p><p>${AI.generateSummary(rep)}</p></div>`;toast('Interview complete')}}};ask()}},
chat(el){let h=S.get('chat',[]);const draw=()=>{$('#ms').innerHTML=h.length?h.map(m=>`<div class="msg ${m.r}">${esc(m.t)}</div>`).join(''):'<p class=mu>No messages yet. Try a suggestion below.</p>';$('#ms').scrollTop=9e9};
 el.innerHTML=`<h1>AI Assistant</h1><div class=card><div id=ms style="min-height:240px;max-height:50vh;overflow:auto"></div><div class=row>${['Explain JavaScript closures','Help me prepare for DBMS','Give me 5 aptitude questions','Explain binary search','Create a 7-day study plan','Prepare me for a frontend interview'].map(t=>`<button data-s="${t}">${t}</button>`).join('')}</div><div class=row><input id=in aria-label=Message placeholder="Ask anything" style="flex:1"><button class=pri id=snd>Send</button><button id=nw>Clear</button></div></div>`;draw();
 const send=async t=>{if(!t.trim())return;h.push({r:'u',t});draw();$('#in').value='';const b=$('#ms');b.insertAdjacentHTML('beforeend','<div class="msg a" id=ty>Typing…</div>');await new Promise(r=>setTimeout(r,600));h.push({r:'a',t:await askAI(t)});S.set('chat',h);draw()};
 $('#snd').onclick=()=>send($('#in').value);$('#in').onkeydown=e=>{if(e.key==='Enter')send(e.target.value)};$('#nw').onclick=()=>{h=[];S.set('chat',h);draw()};el.onclick=e=>{if(e.target.dataset.s)send(e.target.dataset.s)}},
analytics(el){const s=stats(),a=attempts();el.innerHTML=`<h1>Analytics</h1>${a.length?`<div class=grid>${stat('Overall accuracy',s.acc+'%')}${stat('Tests taken',s.n)}</div><div class=grid><div class=card><h3>Score trend</h3><canvas id=c1></canvas></div><div class=card><h3>Topic performance</h3><canvas id=c2></canvas></div></div><div class=card><h3>Strong topics</h3>${s.strong.join(', ')||'-'}<h3>Weak topics</h3>${s.weak.join(', ')||'-'}</div>`:'<div class=card>No attempts yet. Take a test to see analytics.</div>'}`;
 makeChart('c1','line',a.map((x,i)=>'#'+(i+1)),a.map(x=>Math.round(x.score/x.total*100)),'Score %');makeChart('c2','bar',s.tp.map(x=>x[0]),s.tp.map(x=>x[1]),'Accuracy %')},
recommendations(el,u){const s=stats(),r=AI.generateRecommendation(s.weak,u.goal);el.innerHTML=`<h1>Recommended Next</h1>${r.map(x=>`<div class=card>${esc(x)}</div>`).join('')}`},
achievements(el,u){const s={...stats(),streak:u.streak||0,level:u.level||1};el.innerHTML=`<h1>Achievements</h1><div class=grid>${BADGES.map(b=>{const on=b[2](s);return`<div class=card style="opacity:${on?1:.5}"><h3>${on?'🏆':'🔒'} ${b[0]}</h3><p class=mu>${b[1]}</p></div>`}).join('')}</div>`},
reports(el,u){const s=stats();el.innerHTML=`<h1>Performance Report</h1><div class=card><p><b>${esc(u.name)}</b> · ${esc(u.email)} · ${esc(u.goal)}</p><p>Overall accuracy: ${s.acc}% · Questions: ${s.solved} · Tests: ${s.n} · Interviews: ${s.iv}</p>${s.tp.map(t=>`<p>${esc(t[0])} ${t[1]}%${bar(t[1])}</p>`).join('')}<p>Strong: ${s.strong.join(', ')||'-'}<br>Weak: ${s.weak.join(', ')||'-'}</p><p>Recommendations: ${AI.generateRecommendation(s.weak,u.goal).join('; ')}</p></div><button class="pri noprint" onclick="window.print()">Print / Save as PDF</button>`},
profile(el,u){const F=[['name','Name'],['email','Email'],['phone','Phone'],['college','College'],['dept','Department'],['sem','Semester'],['skills','Skills'],['bio','Bio']];el.innerHTML=`<h1>Profile</h1><div class=card>${F.map(f=>`<label>${f[1]}</label><input id=f_${f[0]} value="${esc(u[f[0]])}">`).join('')}<label>Career goal</label><select id=f_goal>${['Software Developer','Data Analyst','AI/ML Engineer','Web Developer','Full Stack Developer','Cybersecurity','Cloud Engineer','Other'].map(g=>`<option ${g===u.goal?'selected':''}>${g}</option>`).join('')}</select><button class=pri id=sv>Save profile</button></div>`;
 $('#sv').onclick=()=>{const us=S.get('users'),x=us.find(z=>z.id===u.id);[...F.map(f=>f[0]),'goal'].forEach(k=>x[k]=$('#f_'+k).value);S.set('users',us);toast('Profile saved')}},
settings(el){el.innerHTML=`<h1>Settings</h1><div class=card><p>AI mode: <b>Demo AI Mode</b> (no API key needed)</p><button id=th>Switch light/dark theme</button> <button id=rs class=warn>Reset all demo data</button></div>`;$('#th').onclick=()=>{const t=S.get('theme','light')==='dark'?'light':'dark';S.set('theme',t);document.documentElement.dataset.theme=t};$('#rs').onclick=()=>{if(confirm('Reset all data?')){S.reset();location.href=base+'login.html'}}},
'f-dashboard'(el){el.innerHTML=`<h1>Faculty Dashboard</h1><div class=grid>${stat('Students',S.get('users').filter(u=>u.role==='STUDENT').length)}${stat('Questions',S.get('questions').length)}</div>`},
'f-students'(el){el.innerHTML=`<h1>Students</h1><div class=card>${table(S.get('users').filter(u=>u.role==='STUDENT'),[['Name','name'],['Email','email'],['Level','level'],['XP','xp']])}</div>`},
'a-dashboard'(el){el.innerHTML=`<h1>Admin Dashboard</h1><div class=grid>${stat('Users',S.get('users').length)}${stat('Questions',S.get('questions').length)}${stat('Attempts',attempts().length)}</div>`},
'a-users'(el){const draw=()=>{const us=S.get('users');el.innerHTML=`<h1>Users</h1><input id=sq placeholder="Search users"><div class=card id=tb>${table(us,[['Name','name'],['Email','email'],['Role','role']],1)}</div>`;$('#tb').onclick=e=>{if(e.target.dataset.del!=null&&confirm('Delete user?')){us.splice(+e.target.dataset.del,1);S.set('users',us);toast('User deleted');draw()}};$('#sq').oninput=e=>{$('#tb').innerHTML=table(us.filter(u=>(u.name+u.email).toLowerCase().includes(e.target.value.toLowerCase())),[['Name','name'],['Email','email'],['Role','role']])}};draw()},
'f-questions'(el){const draw=()=>{const qs=S.get('questions');el.innerHTML=`<h1>Question Bank</h1><div class=card><input id=nq placeholder="Question text"><input id=ns placeholder="Subject"><input id=nt placeholder="Topic"><input id=no placeholder="Options separated by ; (first one correct)"><button class=pri id=ad>Add question</button></div><div class=card id=tb>${table(qs,[['Subject','subject'],['Topic','topic'],['Question','q']],1)}</div>`;
 $('#ad').onclick=()=>{const o=$('#no').value.split(';').map(x=>x.trim()).filter(Boolean);if(!$('#nq').value||o.length<2)return toast('Enter a question and 2+ options');qs.push({id:'Q'+Date.now(),subject:$('#ns').value||'General',topic:$('#nt').value||'General',diff:'Medium',q:$('#nq').value,o,e:'Added by faculty'});S.set('questions',qs);toast('Question added');draw()};
 $('#tb').onclick=e=>{if(e.target.dataset.del!=null&&confirm('Delete question?')){qs.splice(+e.target.dataset.del,1);S.set('questions',qs);toast('Question deleted');draw()}}};draw()}};
P['a-questions']=P['f-questions'];
(function init(){
 if(page==='login'||page==='register'||page==='forgot'){const R=page==='register';document.body.innerHTML=`<div class="card auth"><div class=logo>InterviewAI</div><h2>${page==='forgot'?'Reset password':R?'Create account':'Sign in'}</h2>${page==='forgot'?'<p class=mu>Demo mode: no email is sent. Use the demo accounts in the README.</p>':`${R?'<label>Name</label><input id=nm><label>Role</label><select id=rl><option>STUDENT</option><option>FACULTY</option><option>ADMIN</option></select>':''}<label>Email</label><input id=em type=email><label>Password</label><input id=pw type=password><p id=er class=warn></p><button class=pri id=sb>${R?'Register':'Login'}</button><p class=mu>Demo: student@interviewai.demo / student123<br>faculty@interviewai.demo / faculty123 · admin@interviewai.demo / admin123</p>`}<a href="${R?'login':'register'}.html">${R?'Have an account? Sign in':'Create account'}</a> · <a href=forgot-password.html>Forgot?</a></div>`;
  const go=u=>location.href=u.role==='FACULTY'?'faculty/dashboard.html':u.role==='ADMIN'?'admin/dashboard.html':'dashboard.html';
  if($('#sb'))$('#sb').onclick=()=>{const u=R?Auth.register($('#nm').value||'New User',$('#em').value.trim().toLowerCase(),$('#pw').value,$('#rl').value):Auth.login($('#em').value,$('#pw').value);u?go(u):$('#er').textContent=R?'Email already registered.':'Invalid email or password.'};return}
 const u=Auth.me();if(!u){location.href=base+'login.html';return}
 const allowed={STUDENT:!/^[fa]-/.test(page),FACULTY:/^f-|settings/.test(page),ADMIN:/^a-|settings/.test(page)}[u.role];
 const root=$('#app');if(!allowed){root.innerHTML='<main><div class=card><h2>Unauthorized</h2><p>Your role cannot open this page.</p></div></main>';return}
 root.innerHTML=`<div class=shell><nav class=side aria-label=Main><div class=logo>InterviewAI</div>${NAV[u.role].map(n=>`<a href="${base?'../':''}${n[0]}.html" class="${n[0].split('/').pop()===page.replace(/^[fa]-/,'')?'on':''}">${n[1]}</a>`).join('')}<a href="#" id=lo>Logout</a></nav><main id=pg></main></div>`;
 $('#lo').onclick=e=>{e.preventDefault();Auth.logout()};P[page]($('#pg'),u)})();
